# Generated by Django 4.1.7 on 2023-06-12 18:08

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_tutorial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tutorial',
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name_plural': 'Jobs and Projects'},
        ),
        migrations.AddField(
            model_name='job',
            name='detailed_description',
            field=models.TextField(default='default description'),
        ),
        migrations.AddField(
            model_name='job',
            name='project_video',
            field=embed_video.fields.EmbedVideoField(blank=True, default=None, null=True),
        ),
    ]
