# Generated by Django 4.1.7 on 2023-06-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_delete_tutorial_alter_job_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='date',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
