# Generated by Django 4.1.7 on 2023-06-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_date_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.CharField(blank=True, default=None, max_length=36, null=True),
        ),
    ]
