# Generated by Django 4.1.7 on 2023-06-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_job_or_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.CharField(default='DD/MM/YYYY', max_length=36),
        ),
        migrations.AlterField(
            model_name='job',
            name='detailed_description',
            field=models.TextField(default='placeholder'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_or_project',
            field=models.CharField(choices=[('Job', 'Job'), ('Project', 'Project')], default='Job', max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='summary',
            field=models.CharField(default='placeholder', max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(default='placeholder', max_length=200),
        ),
    ]
