# Generated by Django 4.1.7 on 2023-06-27 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_job_date_alter_job_detailed_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(default='placeholder', max_length=200)),
                ('title', models.CharField(default='placeholder', max_length=200)),
                ('detailed_description', models.TextField(default='placeholder')),
                ('period', models.CharField(default='DD/MM/YYYY', max_length=36)),
                ('image', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'Education',
            },
        ),
    ]
