# Generated by Django 4.1.7 on 2023-06-27 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='site',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
